import jsPDF from "jspdf";

export function generateEnhancedResumePDF(rawText) {
  const doc = new jsPDF("p", "mm", "a4");

  const pageWidth = 210;
  const marginX = 20;
  let y = 25;

  // TITLE
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("AI Enhanced Resume", pageWidth / 2, y, { align: "center" });

  y += 10;
  doc.setDrawColor(34, 139, 84);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 12;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const text = String(rawText || "")
    .replace(/["“”]/g, "")
    .replace(/\*\*/g, "")
    .replace(/^\s*-\s*/gm, "• ")
    .trim();

  const sections = text.split(/\n(?=\d+\.\s)/);

  sections.forEach(section => {
    const lines = section.split("\n");

    // SECTION TITLE
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(lines[0], marginX, y);
    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    lines.slice(1).forEach(line => {
      if (!line.trim()) return;

      const isBullet = line.startsWith("•");
      const content = isBullet ? line.replace(/^•\s*/, "") : line;

      const wrapped = doc.splitTextToSize(
        content,
        pageWidth - marginX * 2 - (isBullet ? 6 : 0)
      );

      wrapped.forEach((w, idx) => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }

        if (isBullet && idx === 0) {
          doc.text("•", marginX, y);
          doc.text(w, marginX + 6, y);
        } else {
          doc.text(w, marginX + (isBullet ? 6 : 0), y);
        }

        y += 6;
      });

      y += 2;
    });

    y += 6;
  });

  // FOOTER
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text(
    "Generated by Curson AI Resume Enhancer",
    pageWidth / 2,
    290,
    { align: "center" }
  );

  doc.save("AI_Enhanced_Resume.pdf");
}
